# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

require 'resolv-replace'
install! 'cocoapods', :deterministic_uuids => false, :preserve_pod_file_structure => true
use_frameworks!

source 'https://github.com/applicaster/CocoaPods.git'
#'git@github.com:applicaster/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'yoga', :path => './node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => './node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => './node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNSVG', :path => './node_modules/react-native-svg'

  pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTWebSocket',
    'RCTActionSheet'
  ]

  pod 'DefaultPlayer', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['APPLICATION_TARGET'] = "ZappiOS"
          config.build_settings['ENABLE_BITCODE'] = 'YES'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
          config.build_settings['OTHER_CFLAGS'] = ['$(inherited)', "-fembed-bitcode"]
          config.build_settings['BITCODE_GENERATION_MODE']  = "bitcode"
          # This works around a unit test issue introduced in Xcode 10.
          # We only apply it to the Debug configuration to avoid bloating the app size
          if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
              config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
          end
      end
  end
end